import type { Player } from '../types';

export const mockPlayers: Player[] = [
  {
    id: 1,
    name: 'James Collins',
    team: 'Crawley Town',
    position: 'Forward',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 32,
      goals: 14,
      assists: 6,
      xG: 12.3,
      xA: 5.1,
      passes_completed: 420,
      pass_accuracy: 78.5,
      tackles: 18,
      interceptions: 12,
      clearances: 8,
      minutes_played: 2680,
      rating: 7.3,
      npxG: 10.5,
      dribbles: 38,
      key_passes: 32,
      aerial_duels_won: 42,
      yellow_cards: 4,
      red_cards: 0,
      fouls_drawn: 35,
      fouls_committed: 22,
    },
    highlights: [
      { id: 'h1', title: 'Goal vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-15', event_type: 'goal', minute: 23 },
      { id: 'h2', title: 'Assist vs Gillingham', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-02', event_type: 'assist', minute: 45 },
    ],
    notes: '',
    ai_summary: 'Clinical finisher with strong movement off the ball. Consistently outperforms xG metrics. Good link-up play with midfielders.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Swindon Town', goals: 2, assists: 0, xG: 1.1, xA: 0.2, minutes: 90, rating: 8.2, dribbles: 2, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Gillingham', goals: 0, assists: 1, xG: 0.3, xA: 0.4, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 2, tackles: 0, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Barrow', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 78, rating: 6.4, dribbles: 0, key_passes: 0, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Doncaster Rovers', goals: 1, assists: 0, xG: 0.7, xA: 0.1, minutes: 90, rating: 7.5, dribbles: 2, key_passes: 1, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Accrington Stanley', goals: 0, assists: 1, xG: 0.4, xA: 0.5, minutes: 85, rating: 7.0, dribbles: 1, key_passes: 2, tackles: 1, interceptions: 1 },
    ],
  },
  {
    id: 2,
    name: 'Ryan Delaney',
    team: 'Morecambe',
    position: 'Defender',
    age: 27,
    nationality: 'Ireland',
    stats: {
      appearances: 38,
      goals: 3,
      assists: 2,
      xG: 2.1,
      xA: 1.5,
      passes_completed: 1120,
      pass_accuracy: 82.3,
      tackles: 72,
      interceptions: 54,
      clearances: 98,
      minutes_played: 3240,
      rating: 7.1,
      npxG: 1.1,
      dribbles: 15,
      key_passes: 18,
      aerial_duels_won: 72,
      yellow_cards: 6,
      red_cards: 0,
      fouls_drawn: 20,
      fouls_committed: 32,
    },
    highlights: [
      { id: 'h3', title: 'Defensive Masterclass vs Barrow', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-20', event_type: 'tackle', minute: 67 },
    ],
    notes: '',
    ai_summary: 'Commanding centre-back with excellent aerial ability. Strong in the tackle and reads the game well. Good distribution from the back.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Barrow', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 7.4, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 2 },
      { match_date: '2025-09-21', opponent: 'Crawley Town', goals: 1, assists: 0, xG: 0.3, xA: 0.0, minutes: 90, rating: 7.8, dribbles: 0, key_passes: 0, tackles: 4, interceptions: 3 },
      { match_date: '2025-09-28', opponent: 'Grimsby Town', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 90, rating: 6.8, dribbles: 1, key_passes: 1, tackles: 2, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Newport County', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 7.0, dribbles: 0, key_passes: 0, tackles: 5, interceptions: 2 },
      { match_date: '2025-10-19', opponent: 'Walsall', goals: 0, assists: 1, xG: 0.0, xA: 0.2, minutes: 90, rating: 7.2, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 4 },
    ],
  },
  {
    id: 3,
    name: 'Alex Pattison',
    team: 'Harrogate Town',
    position: 'Midfielder',
    age: 26,
    nationality: 'England',
    stats: {
      appearances: 35,
      goals: 8,
      assists: 10,
      xG: 6.5,
      xA: 8.9,
      passes_completed: 1450,
      pass_accuracy: 85.2,
      tackles: 42,
      interceptions: 38,
      clearances: 15,
      minutes_played: 3010,
      rating: 7.5,
      npxG: 5.5,
      dribbles: 35,
      key_passes: 58,
      aerial_duels_won: 28,
      yellow_cards: 5,
      red_cards: 0,
      fouls_drawn: 38,
      fouls_committed: 25,
    },
    highlights: [
      { id: 'h4', title: 'Long Range Goal vs Doncaster', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'goal', minute: 34 },
      { id: 'h5', title: 'Playmaking Display vs Grimsby', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-28', event_type: 'assist', minute: 52 },
    ],
    notes: '',
    ai_summary: 'Creative midfielder with excellent vision and passing range. Capable of scoring from distance. Strong work rate off the ball.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Doncaster Rovers', goals: 1, assists: 0, xG: 0.2, xA: 0.3, minutes: 90, rating: 7.8, dribbles: 3, key_passes: 3, tackles: 2, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Salford City', goals: 0, assists: 1, xG: 0.1, xA: 0.5, minutes: 90, rating: 7.3, dribbles: 1, key_passes: 4, tackles: 1, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Mansfield Town', goals: 0, assists: 0, xG: 0.3, xA: 0.2, minutes: 86, rating: 6.7, dribbles: 2, key_passes: 1, tackles: 2, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Tranmere Rovers', goals: 1, assists: 1, xG: 0.4, xA: 0.6, minutes: 90, rating: 8.1, dribbles: 2, key_passes: 3, tackles: 1, interceptions: 1 },
      { match_date: '2025-10-19', opponent: 'Crewe Alexandra', goals: 0, assists: 0, xG: 0.1, xA: 0.1, minutes: 72, rating: 6.5, dribbles: 1, key_passes: 2, tackles: 3, interceptions: 2 },
    ],
  },
  {
    id: 4,
    name: 'Akin Odimayo',
    team: 'Swindon Town',
    position: 'Defender',
    age: 22,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 1,
      assists: 4,
      xG: 0.8,
      xA: 3.2,
      passes_completed: 980,
      pass_accuracy: 80.1,
      tackles: 65,
      interceptions: 48,
      clearances: 72,
      minutes_played: 2520,
      rating: 6.9,
      npxG: 0.4,
      dribbles: 22,
      key_passes: 20,
      aerial_duels_won: 55,
      yellow_cards: 7,
      red_cards: 1,
      fouls_drawn: 18,
      fouls_committed: 35,
    },
    highlights: [
      { id: 'h6', title: 'Recovery Tackle vs Accrington', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-10', event_type: 'tackle', minute: 78 },
    ],
    notes: '',
    ai_summary: 'Athletic right-back with pace and good defensive instincts. Developing his attacking output. Strong one-on-one defender.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Accrington Stanley', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 90, rating: 7.0, dribbles: 1, key_passes: 1, tackles: 4, interceptions: 2 },
      { match_date: '2025-09-21', opponent: 'Stockport County', goals: 0, assists: 1, xG: 0.0, xA: 0.3, minutes: 90, rating: 7.3, dribbles: 2, key_passes: 2, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Bradford City', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 6.5, dribbles: 0, key_passes: 0, tackles: 2, interceptions: 3 },
      { match_date: '2025-10-05', opponent: 'Harrogate Town', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 74, rating: 6.3, dribbles: 1, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Wrexham', goals: 1, assists: 0, xG: 0.2, xA: 0.0, minutes: 90, rating: 7.6, dribbles: 1, key_passes: 0, tackles: 5, interceptions: 2 },
    ],
  },
  {
    id: 5,
    name: 'Danny Johnson',
    team: 'AFC Wimbledon',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 36,
      goals: 18,
      assists: 4,
      xG: 15.7,
      xA: 3.8,
      passes_completed: 310,
      pass_accuracy: 72.4,
      tackles: 14,
      interceptions: 8,
      clearances: 5,
      minutes_played: 2950,
      rating: 7.4,
      npxG: 13.2,
      dribbles: 30,
      key_passes: 22,
      aerial_duels_won: 45,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 40,
      fouls_committed: 18,
    },
    highlights: [
      { id: 'h7', title: 'Hat-trick vs Walsall', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 15 },
      { id: 'h8', title: 'Winning Goal vs Bradford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-22', event_type: 'goal', minute: 88 },
    ],
    notes: '',
    ai_summary: 'Prolific goalscorer with strong positioning and finishing. Experienced at League Two level. Reliable penalty taker.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Walsall', goals: 3, assists: 0, xG: 1.8, xA: 0.1, minutes: 90, rating: 9.1, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Bradford City', goals: 1, assists: 0, xG: 0.6, xA: 0.0, minutes: 90, rating: 7.4, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-28', opponent: 'Morecambe', goals: 0, assists: 0, xG: 0.3, xA: 0.1, minutes: 85, rating: 6.2, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Grimsby Town', goals: 0, assists: 1, xG: 0.2, xA: 0.4, minutes: 90, rating: 6.9, dribbles: 2, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Crawley Town', goals: 1, assists: 0, xG: 0.8, xA: 0.0, minutes: 90, rating: 7.5, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
    ],
  },
  {
    id: 6,
    name: 'Jake Taylor',
    team: 'Barrow',
    position: 'Midfielder',
    age: 25,
    nationality: 'England',
    stats: {
      appearances: 34,
      goals: 5,
      assists: 7,
      xG: 4.2,
      xA: 6.8,
      passes_completed: 1280,
      pass_accuracy: 83.7,
      tackles: 55,
      interceptions: 40,
      clearances: 20,
      minutes_played: 2890,
      rating: 7.0,
      npxG: 3.4,
      dribbles: 28,
      key_passes: 48,
      aerial_duels_won: 32,
      yellow_cards: 5,
      red_cards: 0,
      fouls_drawn: 30,
      fouls_committed: 28,
    },
    highlights: [
      { id: 'h9', title: 'Box-to-Box Display vs Newport', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-28', event_type: 'other', minute: 40 },
    ],
    notes: '',
    ai_summary: 'Energetic box-to-box midfielder with good passing and tackling. Provides balance between attack and defense. Consistent performer.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Newport County', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 90, rating: 7.2, dribbles: 1, key_passes: 3, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Walsall', goals: 1, assists: 0, xG: 0.3, xA: 0.1, minutes: 90, rating: 7.6, dribbles: 2, key_passes: 2, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Swindon Town', goals: 0, assists: 0, xG: 0.1, xA: 0.2, minutes: 90, rating: 6.5, dribbles: 0, key_passes: 1, tackles: 4, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Salford City', goals: 0, assists: 1, xG: 0.0, xA: 0.5, minutes: 82, rating: 7.0, dribbles: 1, key_passes: 3, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Mansfield Town', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 90, rating: 6.8, dribbles: 0, key_passes: 1, tackles: 2, interceptions: 3 },
    ],
  },
  {
    id: 7,
    name: 'Owen Dale',
    team: 'Gillingham',
    position: 'Forward',
    age: 23,
    nationality: 'Wales',
    stats: {
      appearances: 28,
      goals: 7,
      assists: 9,
      xG: 5.9,
      xA: 7.4,
      passes_completed: 380,
      pass_accuracy: 74.8,
      tackles: 20,
      interceptions: 10,
      clearances: 4,
      minutes_played: 2210,
      rating: 7.2,
      npxG: 4.9,
      dribbles: 48,
      key_passes: 38,
      aerial_duels_won: 18,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 42,
      fouls_committed: 15,
    },
    highlights: [
      { id: 'h10', title: 'Solo Goal vs Salford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-18', event_type: 'goal', minute: 61 },
    ],
    notes: '',
    ai_summary: 'Tricky winger with excellent dribbling and crossing ability. Creates chances consistently. Developing his end product.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Salford City', goals: 1, assists: 0, xG: 0.3, xA: 0.2, minutes: 90, rating: 7.9, dribbles: 4, key_passes: 2, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Crewe Alexandra', goals: 0, assists: 1, xG: 0.1, xA: 0.6, minutes: 90, rating: 7.4, dribbles: 3, key_passes: 3, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-28', opponent: 'Stockport County', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 68, rating: 6.3, dribbles: 1, key_passes: 0, tackles: 1, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Tranmere Rovers', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 85, rating: 7.1, dribbles: 2, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Barrow', goals: 1, assists: 0, xG: 0.5, xA: 0.0, minutes: 90, rating: 7.6, dribbles: 3, key_passes: 1, tackles: 1, interceptions: 0 },
    ],
  },
  {
    id: 8,
    name: 'Kellan Gordon',
    team: 'Doncaster Rovers',
    position: 'Defender',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 33,
      goals: 2,
      assists: 5,
      xG: 1.4,
      xA: 4.1,
      passes_completed: 1050,
      pass_accuracy: 81.6,
      tackles: 58,
      interceptions: 42,
      clearances: 35,
      minutes_played: 2780,
      rating: 7.0,
      npxG: 0.8,
      dribbles: 24,
      key_passes: 22,
      aerial_duels_won: 52,
      yellow_cards: 4,
      red_cards: 0,
      fouls_drawn: 22,
      fouls_committed: 30,
    },
    highlights: [
      { id: 'h11', title: 'Overlapping Run Goal vs Tranmere', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-08', event_type: 'goal', minute: 72 },
    ],
    notes: '',
    ai_summary: 'Attack-minded full-back with pace and crossing ability. Defensively solid and positionally aware. Good stamina for overlap runs.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Tranmere Rovers', goals: 1, assists: 0, xG: 0.2, xA: 0.1, minutes: 90, rating: 7.5, dribbles: 2, key_passes: 1, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Harrogate Town', goals: 0, assists: 1, xG: 0.0, xA: 0.3, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 2, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Morecambe', goals: 0, assists: 0, xG: 0.0, xA: 0.0, minutes: 90, rating: 6.6, dribbles: 0, key_passes: 0, tackles: 4, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'AFC Wimbledon', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 90, rating: 7.2, dribbles: 1, key_passes: 2, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Gillingham', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 82, rating: 6.7, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 2 },
    ],
  },
  {
    id: 9,
    name: 'Liam Sercombe',
    team: 'Newport County',
    position: 'Midfielder',
    age: 31,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 6,
      assists: 8,
      xG: 5.3,
      xA: 7.1,
      passes_completed: 1180,
      pass_accuracy: 84.0,
      tackles: 35,
      interceptions: 30,
      clearances: 12,
      minutes_played: 2540,
      rating: 7.2,
      npxG: 4.3,
      dribbles: 22,
      key_passes: 52,
      aerial_duels_won: 25,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 28,
      fouls_committed: 20,
    },
    highlights: [
      { id: 'h12', title: 'Free Kick Goal vs Crewe', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-25', event_type: 'goal', minute: 55 },
    ],
    notes: '',
    ai_summary: 'Experienced midfielder with excellent set-piece delivery. Strong leadership qualities. Good range of passing and game management.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Crewe Alexandra', goals: 1, assists: 0, xG: 0.1, xA: 0.2, minutes: 90, rating: 7.8, dribbles: 0, key_passes: 3, tackles: 1, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Barrow', goals: 0, assists: 1, xG: 0.2, xA: 0.5, minutes: 90, rating: 7.3, dribbles: 1, key_passes: 4, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Doncaster Rovers', goals: 0, assists: 0, xG: 0.1, xA: 0.1, minutes: 78, rating: 6.5, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Swindon Town', goals: 0, assists: 1, xG: 0.0, xA: 0.6, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 3, tackles: 0, interceptions: 1 },
      { match_date: '2025-10-19', opponent: 'Accrington Stanley', goals: 1, assists: 0, xG: 0.4, xA: 0.0, minutes: 85, rating: 7.5, dribbles: 0, key_passes: 2, tackles: 2, interceptions: 2 },
    ],
  },
  {
    id: 10,
    name: 'Paul Mullin',
    team: 'Wrexham',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 25,
      goals: 12,
      assists: 3,
      xG: 10.8,
      xA: 2.9,
      passes_completed: 280,
      pass_accuracy: 70.5,
      tackles: 10,
      interceptions: 6,
      clearances: 3,
      minutes_played: 1980,
      rating: 7.6,
      npxG: 9.0,
      dribbles: 32,
      key_passes: 20,
      aerial_duels_won: 38,
      yellow_cards: 2,
      red_cards: 0,
      fouls_drawn: 32,
      fouls_committed: 16,
    },
    highlights: [
      { id: 'h13', title: 'Brace vs Mansfield Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-06', event_type: 'goal', minute: 29 },
      { id: 'h14', title: 'Overhead Kick vs Stockport', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-20', event_type: 'goal', minute: 43 },
    ],
    notes: '',
    ai_summary: 'Natural goalscorer with predatory instincts in the box. Good aerial ability for his size. Proven at this level with impressive goal record.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Mansfield Town', goals: 2, assists: 0, xG: 1.3, xA: 0.1, minutes: 90, rating: 8.5, dribbles: 2, key_passes: 1, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Stockport County', goals: 1, assists: 0, xG: 0.5, xA: 0.0, minutes: 90, rating: 7.8, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Crawley Town', goals: 0, assists: 0, xG: 0.3, xA: 0.2, minutes: 70, rating: 6.4, dribbles: 1, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Gillingham', goals: 0, assists: 1, xG: 0.2, xA: 0.3, minutes: 90, rating: 7.0, dribbles: 0, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Newport County', goals: 1, assists: 0, xG: 0.7, xA: 0.0, minutes: 82, rating: 7.4, dribbles: 2, key_passes: 0, tackles: 1, interceptions: 0 },
    ],
  },
];
