import type { Player } from '../types';

export const mockPlayers: Player[] = [
  {
    id: 1,
    name: 'James Collins',
    team: 'Crawley Town',
    position: 'Forward',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 32,
      goals: 14,
      assists: 6,
      xG: 12.3,
      xA: 5.1,
      passes_completed: 420,
      pass_accuracy: 78.5,
      tackles: 18,
      interceptions: 12,
      clearances: 8,
      minutes_played: 2680,
    },
    highlights: [
      { id: 'h1', title: 'Goal vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-15' },
      { id: 'h2', title: 'Assist vs Gillingham', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-02' },
    ],
    notes: '',
    ai_summary: 'Clinical finisher with strong movement off the ball. Consistently outperforms xG metrics. Good link-up play with midfielders.',
  },
  {
    id: 2,
    name: 'Ryan Delaney',
    team: 'Morecambe',
    position: 'Defender',
    age: 27,
    nationality: 'Ireland',
    stats: {
      appearances: 38,
      goals: 3,
      assists: 2,
      xG: 2.1,
      xA: 1.5,
      passes_completed: 1120,
      pass_accuracy: 82.3,
      tackles: 72,
      interceptions: 54,
      clearances: 98,
      minutes_played: 3240,
    },
    highlights: [
      { id: 'h3', title: 'Defensive Masterclass vs Barrow', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-20' },
    ],
    notes: '',
    ai_summary: 'Commanding centre-back with excellent aerial ability. Strong in the tackle and reads the game well. Good distribution from the back.',
  },
  {
    id: 3,
    name: 'Alex Pattison',
    team: 'Harrogate Town',
    position: 'Midfielder',
    age: 26,
    nationality: 'England',
    stats: {
      appearances: 35,
      goals: 8,
      assists: 10,
      xG: 6.5,
      xA: 8.9,
      passes_completed: 1450,
      pass_accuracy: 85.2,
      tackles: 42,
      interceptions: 38,
      clearances: 15,
      minutes_played: 3010,
    },
    highlights: [
      { id: 'h4', title: 'Long Range Goal vs Doncaster', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14' },
      { id: 'h5', title: 'Playmaking Display vs Grimsby', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-28' },
    ],
    notes: '',
    ai_summary: 'Creative midfielder with excellent vision and passing range. Capable of scoring from distance. Strong work rate off the ball.',
  },
  {
    id: 4,
    name: 'Akin Odimayo',
    team: 'Swindon Town',
    position: 'Defender',
    age: 22,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 1,
      assists: 4,
      xG: 0.8,
      xA: 3.2,
      passes_completed: 980,
      pass_accuracy: 80.1,
      tackles: 65,
      interceptions: 48,
      clearances: 72,
      minutes_played: 2520,
    },
    highlights: [
      { id: 'h6', title: 'Recovery Tackle vs Accrington', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-10' },
    ],
    notes: '',
    ai_summary: 'Athletic right-back with pace and good defensive instincts. Developing his attacking output. Strong one-on-one defender.',
  },
  {
    id: 5,
    name: 'Danny Johnson',
    team: 'AFC Wimbledon',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 36,
      goals: 18,
      assists: 4,
      xG: 15.7,
      xA: 3.8,
      passes_completed: 310,
      pass_accuracy: 72.4,
      tackles: 14,
      interceptions: 8,
      clearances: 5,
      minutes_played: 2950,
    },
    highlights: [
      { id: 'h7', title: 'Hat-trick vs Walsall', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05' },
      { id: 'h8', title: 'Winning Goal vs Bradford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-22' },
    ],
    notes: '',
    ai_summary: 'Prolific goalscorer with strong positioning and finishing. Experienced at League Two level. Reliable penalty taker.',
  },
  {
    id: 6,
    name: 'Jake Taylor',
    team: 'Barrow',
    position: 'Midfielder',
    age: 25,
    nationality: 'England',
    stats: {
      appearances: 34,
      goals: 5,
      assists: 7,
      xG: 4.2,
      xA: 6.8,
      passes_completed: 1280,
      pass_accuracy: 83.7,
      tackles: 55,
      interceptions: 40,
      clearances: 20,
      minutes_played: 2890,
    },
    highlights: [
      { id: 'h9', title: 'Box-to-Box Display vs Newport', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-28' },
    ],
    notes: '',
    ai_summary: 'Energetic box-to-box midfielder with good passing and tackling. Provides balance between attack and defense. Consistent performer.',
  },
  {
    id: 7,
    name: 'Owen Dale',
    team: 'Gillingham',
    position: 'Forward',
    age: 23,
    nationality: 'Wales',
    stats: {
      appearances: 28,
      goals: 7,
      assists: 9,
      xG: 5.9,
      xA: 7.4,
      passes_completed: 380,
      pass_accuracy: 74.8,
      tackles: 20,
      interceptions: 10,
      clearances: 4,
      minutes_played: 2210,
    },
    highlights: [
      { id: 'h10', title: 'Solo Goal vs Salford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-18' },
    ],
    notes: '',
    ai_summary: 'Tricky winger with excellent dribbling and crossing ability. Creates chances consistently. Developing his end product.',
  },
  {
    id: 8,
    name: 'Kellan Gordon',
    team: 'Doncaster Rovers',
    position: 'Defender',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 33,
      goals: 2,
      assists: 5,
      xG: 1.4,
      xA: 4.1,
      passes_completed: 1050,
      pass_accuracy: 81.6,
      tackles: 58,
      interceptions: 42,
      clearances: 35,
      minutes_played: 2780,
    },
    highlights: [
      { id: 'h11', title: 'Overlapping Run Goal vs Tranmere', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-08' },
    ],
    notes: '',
    ai_summary: 'Attack-minded full-back with pace and crossing ability. Defensively solid and positionally aware. Good stamina for overlap runs.',
  },
  {
    id: 9,
    name: 'Liam Sercombe',
    team: 'Newport County',
    position: 'Midfielder',
    age: 31,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 6,
      assists: 8,
      xG: 5.3,
      xA: 7.1,
      passes_completed: 1180,
      pass_accuracy: 84.0,
      tackles: 35,
      interceptions: 30,
      clearances: 12,
      minutes_played: 2540,
    },
    highlights: [
      { id: 'h12', title: 'Free Kick Goal vs Crewe', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-25' },
    ],
    notes: '',
    ai_summary: 'Experienced midfielder with excellent set-piece delivery. Strong leadership qualities. Good range of passing and game management.',
  },
  {
    id: 10,
    name: 'Paul Mullin',
    team: 'Wrexham',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 25,
      goals: 12,
      assists: 3,
      xG: 10.8,
      xA: 2.9,
      passes_completed: 280,
      pass_accuracy: 70.5,
      tackles: 10,
      interceptions: 6,
      clearances: 3,
      minutes_played: 1980,
    },
    highlights: [
      { id: 'h13', title: 'Brace vs Mansfield Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-06' },
      { id: 'h14', title: 'Overhead Kick vs Stockport', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-20' },
    ],
    notes: '',
    ai_summary: 'Natural goalscorer with predatory instincts in the box. Good aerial ability for his size. Proven at this level with impressive goal record.',
  },
];
