import type { Player, Team, LeagueEntry } from '../types';

export const mockPlayers: Player[] = [
  {
    id: 1,
    name: 'James Collins',
    team: 'Crawley Town',
    position: 'Forward',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 32,
      goals: 14,
      assists: 6,
      xG: 12.3,
      xA: 5.1,
      passes_completed: 420,
      pass_accuracy: 78.5,
      tackles: 18,
      interceptions: 12,
      clearances: 8,
      minutes_played: 2680,
      rating: 7.3,
      npxG: 10.5,
      dribbles: 38,
      key_passes: 32,
      aerial_duels_won: 42,
      yellow_cards: 4,
      red_cards: 0,
      fouls_drawn: 35,
      fouls_committed: 22,
    },
    highlights: [
      { id: 'h1', title: 'Goal vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-15', event_type: 'goal', minute: 23 },
      { id: 'h1b', title: '1st Goal vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'goal', minute: 35 },
      { id: 'h1c', title: '2nd Goal vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'goal', minute: 71 },
      { id: 'h1d', title: 'Goal vs Doncaster Rovers', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 58 },
      { id: 'h2', title: 'Assist vs Gillingham', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-02', event_type: 'assist', minute: 45 },
      { id: 'h2b', title: 'Assist vs Accrington Stanley', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'assist', minute: 32 },
    ],
    notes: '',
    ai_summary: 'Clinical finisher with strong movement off the ball. Consistently outperforms xG metrics. Good link-up play with midfielders.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Swindon Town', goals: 2, assists: 0, xG: 1.1, xA: 0.2, minutes: 90, rating: 8.2, dribbles: 2, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Gillingham', goals: 0, assists: 1, xG: 0.3, xA: 0.4, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 2, tackles: 0, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Barrow', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 78, rating: 6.4, dribbles: 0, key_passes: 0, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Doncaster Rovers', goals: 1, assists: 0, xG: 0.7, xA: 0.1, minutes: 90, rating: 7.5, dribbles: 2, key_passes: 1, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Accrington Stanley', goals: 0, assists: 1, xG: 0.4, xA: 0.5, minutes: 85, rating: 7.0, dribbles: 1, key_passes: 2, tackles: 1, interceptions: 1 },
    ],
  },
  {
    id: 2,
    name: 'Ryan Delaney',
    team: 'Morecambe',
    position: 'Defender',
    age: 27,
    nationality: 'Ireland',
    stats: {
      appearances: 38,
      goals: 3,
      assists: 2,
      xG: 2.1,
      xA: 1.5,
      passes_completed: 1120,
      pass_accuracy: 82.3,
      tackles: 72,
      interceptions: 54,
      clearances: 98,
      minutes_played: 3240,
      rating: 7.1,
      npxG: 1.1,
      dribbles: 15,
      key_passes: 18,
      aerial_duels_won: 72,
      yellow_cards: 6,
      red_cards: 0,
      fouls_drawn: 20,
      fouls_committed: 32,
    },
    highlights: [
      { id: 'h3', title: 'Goal vs Grimsby Town (Header)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-28', event_type: 'goal', minute: 12 },
      { id: 'h3b', title: 'Goal vs Crawley Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'goal', minute: 44 },
      { id: 'h3c', title: 'Goal vs Newport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 88 },
      { id: 'h3d', title: 'Assist vs Walsall', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'assist', minute: 67 },
      { id: 'h3e', title: 'Defensive Masterclass vs Barrow', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-20', event_type: 'tackle', minute: 67 },
    ],
    notes: '',
    ai_summary: 'Commanding centre-back with excellent aerial ability. Strong in the tackle and reads the game well. Good distribution from the back.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Barrow', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 7.4, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 2 },
      { match_date: '2025-09-21', opponent: 'Crawley Town', goals: 1, assists: 0, xG: 0.3, xA: 0.0, minutes: 90, rating: 7.8, dribbles: 0, key_passes: 0, tackles: 4, interceptions: 3 },
      { match_date: '2025-09-28', opponent: 'Grimsby Town', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 90, rating: 6.8, dribbles: 1, key_passes: 1, tackles: 2, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Newport County', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 7.0, dribbles: 0, key_passes: 0, tackles: 5, interceptions: 2 },
      { match_date: '2025-10-19', opponent: 'Walsall', goals: 0, assists: 1, xG: 0.0, xA: 0.2, minutes: 90, rating: 7.2, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 4 },
    ],
  },
  {
    id: 3,
    name: 'Alex Pattison',
    team: 'Harrogate Town',
    position: 'Midfielder',
    age: 26,
    nationality: 'England',
    stats: {
      appearances: 35,
      goals: 8,
      assists: 10,
      xG: 6.5,
      xA: 8.9,
      passes_completed: 1450,
      pass_accuracy: 85.2,
      tackles: 42,
      interceptions: 38,
      clearances: 15,
      minutes_played: 3010,
      rating: 7.5,
      npxG: 5.5,
      dribbles: 35,
      key_passes: 58,
      aerial_duels_won: 28,
      yellow_cards: 5,
      red_cards: 0,
      fouls_drawn: 38,
      fouls_committed: 25,
    },
    highlights: [
      { id: 'h4', title: 'Long Range Goal vs Doncaster', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'goal', minute: 34 },
      { id: 'h4b', title: 'Goal vs Tranmere Rovers', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 15 },
      { id: 'h5', title: 'Assist vs Grimsby', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-28', event_type: 'assist', minute: 52 },
      { id: 'h5b', title: 'Assist vs Salford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'assist', minute: 28 },
      { id: 'h5c', title: 'Assist vs Tranmere Rovers', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 72 },
    ],
    notes: '',
    ai_summary: 'Creative midfielder with excellent vision and passing range. Capable of scoring from distance. Strong work rate off the ball.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Doncaster Rovers', goals: 1, assists: 0, xG: 0.2, xA: 0.3, minutes: 90, rating: 7.8, dribbles: 3, key_passes: 3, tackles: 2, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Salford City', goals: 0, assists: 1, xG: 0.1, xA: 0.5, minutes: 90, rating: 7.3, dribbles: 1, key_passes: 4, tackles: 1, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Mansfield Town', goals: 0, assists: 0, xG: 0.3, xA: 0.2, minutes: 86, rating: 6.7, dribbles: 2, key_passes: 1, tackles: 2, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Tranmere Rovers', goals: 1, assists: 1, xG: 0.4, xA: 0.6, minutes: 90, rating: 8.1, dribbles: 2, key_passes: 3, tackles: 1, interceptions: 1 },
      { match_date: '2025-10-19', opponent: 'Crewe Alexandra', goals: 0, assists: 0, xG: 0.1, xA: 0.1, minutes: 72, rating: 6.5, dribbles: 1, key_passes: 2, tackles: 3, interceptions: 2 },
    ],
  },
  {
    id: 4,
    name: 'Akin Odimayo',
    team: 'Swindon Town',
    position: 'Defender',
    age: 22,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 1,
      assists: 4,
      xG: 0.8,
      xA: 3.2,
      passes_completed: 980,
      pass_accuracy: 80.1,
      tackles: 65,
      interceptions: 48,
      clearances: 72,
      minutes_played: 2520,
      rating: 6.9,
      npxG: 0.4,
      dribbles: 22,
      key_passes: 20,
      aerial_duels_won: 55,
      yellow_cards: 7,
      red_cards: 1,
      fouls_drawn: 18,
      fouls_committed: 35,
    },
    highlights: [
      { id: 'h6', title: 'Goal vs Wrexham', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'goal', minute: 78 },
      { id: 'h6b', title: 'Assist vs Stockport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'assist', minute: 33 },
      { id: 'h6c', title: 'Recovery Tackle vs Accrington', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-10', event_type: 'tackle', minute: 78 },
    ],
    notes: '',
    ai_summary: 'Athletic right-back with pace and good defensive instincts. Developing his attacking output. Strong one-on-one defender.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Accrington Stanley', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 90, rating: 7.0, dribbles: 1, key_passes: 1, tackles: 4, interceptions: 2 },
      { match_date: '2025-09-21', opponent: 'Stockport County', goals: 0, assists: 1, xG: 0.0, xA: 0.3, minutes: 90, rating: 7.3, dribbles: 2, key_passes: 2, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Bradford City', goals: 0, assists: 0, xG: 0.1, xA: 0.0, minutes: 90, rating: 6.5, dribbles: 0, key_passes: 0, tackles: 2, interceptions: 3 },
      { match_date: '2025-10-05', opponent: 'Harrogate Town', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 74, rating: 6.3, dribbles: 1, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Wrexham', goals: 1, assists: 0, xG: 0.2, xA: 0.0, minutes: 90, rating: 7.6, dribbles: 1, key_passes: 0, tackles: 5, interceptions: 2 },
    ],
  },
  {
    id: 5,
    name: 'Danny Johnson',
    team: 'AFC Wimbledon',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 36,
      goals: 18,
      assists: 4,
      xG: 15.7,
      xA: 3.8,
      passes_completed: 310,
      pass_accuracy: 72.4,
      tackles: 14,
      interceptions: 8,
      clearances: 5,
      minutes_played: 2950,
      rating: 7.4,
      npxG: 13.2,
      dribbles: 30,
      key_passes: 22,
      aerial_duels_won: 45,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 40,
      fouls_committed: 18,
    },
    highlights: [
      { id: 'h7', title: 'Hat-trick vs Walsall (1st)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 15 },
      { id: 'h7b', title: 'Hat-trick vs Walsall (2nd)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 34 },
      { id: 'h7c', title: 'Hat-trick vs Walsall (3rd)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 72 },
      { id: 'h8', title: 'Winning Goal vs Bradford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-22', event_type: 'goal', minute: 88 },
      { id: 'h8b', title: 'Goal vs Crawley Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'goal', minute: 55 },
      { id: 'h8c', title: 'Assist vs Grimsby Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 41 },
    ],
    notes: '',
    ai_summary: 'Prolific goalscorer with strong positioning and finishing. Experienced at League Two level. Reliable penalty taker.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Walsall', goals: 3, assists: 0, xG: 1.8, xA: 0.1, minutes: 90, rating: 9.1, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Bradford City', goals: 1, assists: 0, xG: 0.6, xA: 0.0, minutes: 90, rating: 7.4, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-28', opponent: 'Morecambe', goals: 0, assists: 0, xG: 0.3, xA: 0.1, minutes: 85, rating: 6.2, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Grimsby Town', goals: 0, assists: 1, xG: 0.2, xA: 0.4, minutes: 90, rating: 6.9, dribbles: 2, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Crawley Town', goals: 1, assists: 0, xG: 0.8, xA: 0.0, minutes: 90, rating: 7.5, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
    ],
  },
  {
    id: 6,
    name: 'Jake Taylor',
    team: 'Barrow',
    position: 'Midfielder',
    age: 25,
    nationality: 'England',
    stats: {
      appearances: 34,
      goals: 5,
      assists: 7,
      xG: 4.2,
      xA: 6.8,
      passes_completed: 1280,
      pass_accuracy: 83.7,
      tackles: 55,
      interceptions: 40,
      clearances: 20,
      minutes_played: 2890,
      rating: 7.0,
      npxG: 3.4,
      dribbles: 28,
      key_passes: 48,
      aerial_duels_won: 32,
      yellow_cards: 5,
      red_cards: 0,
      fouls_drawn: 30,
      fouls_committed: 28,
    },
    highlights: [
      { id: 'h9', title: 'Goal vs Newport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'goal', minute: 40 },
      { id: 'h9b', title: 'Goal vs Walsall', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'goal', minute: 62 },
      { id: 'h9c', title: 'Assist vs Newport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-14', event_type: 'assist', minute: 22 },
      { id: 'h9d', title: 'Assist vs Salford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 51 },
    ],
    notes: '',
    ai_summary: 'Energetic box-to-box midfielder with good passing and tackling. Provides balance between attack and defense. Consistent performer.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Newport County', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 90, rating: 7.2, dribbles: 1, key_passes: 3, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Walsall', goals: 1, assists: 0, xG: 0.3, xA: 0.1, minutes: 90, rating: 7.6, dribbles: 2, key_passes: 2, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Swindon Town', goals: 0, assists: 0, xG: 0.1, xA: 0.2, minutes: 90, rating: 6.5, dribbles: 0, key_passes: 1, tackles: 4, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Salford City', goals: 0, assists: 1, xG: 0.0, xA: 0.5, minutes: 82, rating: 7.0, dribbles: 1, key_passes: 3, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Mansfield Town', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 90, rating: 6.8, dribbles: 0, key_passes: 1, tackles: 2, interceptions: 3 },
    ],
  },
  {
    id: 7,
    name: 'Owen Dale',
    team: 'Gillingham',
    position: 'Forward',
    age: 23,
    nationality: 'Wales',
    stats: {
      appearances: 28,
      goals: 7,
      assists: 9,
      xG: 5.9,
      xA: 7.4,
      passes_completed: 380,
      pass_accuracy: 74.8,
      tackles: 20,
      interceptions: 10,
      clearances: 4,
      minutes_played: 2210,
      rating: 7.2,
      npxG: 4.9,
      dribbles: 48,
      key_passes: 38,
      aerial_duels_won: 18,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 42,
      fouls_committed: 15,
    },
    highlights: [
      { id: 'h10', title: 'Solo Goal vs Salford City', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-18', event_type: 'goal', minute: 61 },
      { id: 'h10b', title: 'Goal vs Barrow', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'goal', minute: 74 },
      { id: 'h10c', title: 'Assist vs Crewe Alexandra', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'assist', minute: 19 },
      { id: 'h10d', title: 'Assist vs Tranmere Rovers', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 37 },
    ],
    notes: '',
    ai_summary: 'Tricky winger with excellent dribbling and crossing ability. Creates chances consistently. Developing his end product.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Salford City', goals: 1, assists: 0, xG: 0.3, xA: 0.2, minutes: 90, rating: 7.9, dribbles: 4, key_passes: 2, tackles: 1, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Crewe Alexandra', goals: 0, assists: 1, xG: 0.1, xA: 0.6, minutes: 90, rating: 7.4, dribbles: 3, key_passes: 3, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-28', opponent: 'Stockport County', goals: 0, assists: 0, xG: 0.2, xA: 0.1, minutes: 68, rating: 6.3, dribbles: 1, key_passes: 0, tackles: 1, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'Tranmere Rovers', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 85, rating: 7.1, dribbles: 2, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Barrow', goals: 1, assists: 0, xG: 0.5, xA: 0.0, minutes: 90, rating: 7.6, dribbles: 3, key_passes: 1, tackles: 1, interceptions: 0 },
    ],
  },
  {
    id: 8,
    name: 'Kellan Gordon',
    team: 'Doncaster Rovers',
    position: 'Defender',
    age: 24,
    nationality: 'England',
    stats: {
      appearances: 33,
      goals: 2,
      assists: 5,
      xG: 1.4,
      xA: 4.1,
      passes_completed: 1050,
      pass_accuracy: 81.6,
      tackles: 58,
      interceptions: 42,
      clearances: 35,
      minutes_played: 2780,
      rating: 7.0,
      npxG: 0.8,
      dribbles: 24,
      key_passes: 22,
      aerial_duels_won: 52,
      yellow_cards: 4,
      red_cards: 0,
      fouls_drawn: 22,
      fouls_committed: 30,
    },
    highlights: [
      { id: 'h11', title: 'Overlapping Run Goal vs Tranmere', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-11-08', event_type: 'goal', minute: 72 },
      { id: 'h11b', title: 'Goal vs Newport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'goal', minute: 83 },
      { id: 'h11c', title: 'Assist vs Harrogate Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'assist', minute: 25 },
      { id: 'h11d', title: 'Assist vs AFC Wimbledon', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 57 },
    ],
    notes: '',
    ai_summary: 'Attack-minded full-back with pace and crossing ability. Defensively solid and positionally aware. Good stamina for overlap runs.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Tranmere Rovers', goals: 1, assists: 0, xG: 0.2, xA: 0.1, minutes: 90, rating: 7.5, dribbles: 2, key_passes: 1, tackles: 3, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Harrogate Town', goals: 0, assists: 1, xG: 0.0, xA: 0.3, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 2, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Morecambe', goals: 0, assists: 0, xG: 0.0, xA: 0.0, minutes: 90, rating: 6.6, dribbles: 0, key_passes: 0, tackles: 4, interceptions: 1 },
      { match_date: '2025-10-05', opponent: 'AFC Wimbledon', goals: 0, assists: 1, xG: 0.1, xA: 0.4, minutes: 90, rating: 7.2, dribbles: 1, key_passes: 2, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Gillingham', goals: 0, assists: 0, xG: 0.0, xA: 0.1, minutes: 82, rating: 6.7, dribbles: 0, key_passes: 1, tackles: 3, interceptions: 2 },
    ],
  },
  {
    id: 9,
    name: 'Liam Sercombe',
    team: 'Newport County',
    position: 'Midfielder',
    age: 31,
    nationality: 'England',
    stats: {
      appearances: 30,
      goals: 6,
      assists: 8,
      xG: 5.3,
      xA: 7.1,
      passes_completed: 1180,
      pass_accuracy: 84.0,
      tackles: 35,
      interceptions: 30,
      clearances: 12,
      minutes_played: 2540,
      rating: 7.2,
      npxG: 4.3,
      dribbles: 22,
      key_passes: 52,
      aerial_duels_won: 25,
      yellow_cards: 3,
      red_cards: 0,
      fouls_drawn: 28,
      fouls_committed: 20,
    },
    highlights: [
      { id: 'h12', title: 'Free Kick Goal vs Crewe', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-25', event_type: 'goal', minute: 55 },
      { id: 'h12b', title: 'Goal vs Accrington Stanley', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'goal', minute: 38 },
      { id: 'h12c', title: 'Assist vs Barrow', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-21', event_type: 'assist', minute: 14 },
      { id: 'h12d', title: 'Assist vs Swindon Town', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 66 },
    ],
    notes: '',
    ai_summary: 'Experienced midfielder with excellent set-piece delivery. Strong leadership qualities. Good range of passing and game management.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Crewe Alexandra', goals: 1, assists: 0, xG: 0.1, xA: 0.2, minutes: 90, rating: 7.8, dribbles: 0, key_passes: 3, tackles: 1, interceptions: 1 },
      { match_date: '2025-09-21', opponent: 'Barrow', goals: 0, assists: 1, xG: 0.2, xA: 0.5, minutes: 90, rating: 7.3, dribbles: 1, key_passes: 4, tackles: 2, interceptions: 2 },
      { match_date: '2025-09-28', opponent: 'Doncaster Rovers', goals: 0, assists: 0, xG: 0.1, xA: 0.1, minutes: 78, rating: 6.5, dribbles: 0, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Swindon Town', goals: 0, assists: 1, xG: 0.0, xA: 0.6, minutes: 90, rating: 7.1, dribbles: 1, key_passes: 3, tackles: 0, interceptions: 1 },
      { match_date: '2025-10-19', opponent: 'Accrington Stanley', goals: 1, assists: 0, xG: 0.4, xA: 0.0, minutes: 85, rating: 7.5, dribbles: 0, key_passes: 2, tackles: 2, interceptions: 2 },
    ],
  },
  {
    id: 10,
    name: 'Paul Mullin',
    team: 'Wrexham',
    position: 'Forward',
    age: 29,
    nationality: 'England',
    stats: {
      appearances: 25,
      goals: 12,
      assists: 3,
      xG: 10.8,
      xA: 2.9,
      passes_completed: 280,
      pass_accuracy: 70.5,
      tackles: 10,
      interceptions: 6,
      clearances: 3,
      minutes_played: 1980,
      rating: 7.6,
      npxG: 9.0,
      dribbles: 32,
      key_passes: 20,
      aerial_duels_won: 38,
      yellow_cards: 2,
      red_cards: 0,
      fouls_drawn: 32,
      fouls_committed: 16,
    },
    highlights: [
      { id: 'h13', title: 'Brace vs Mansfield Town (1st)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-06', event_type: 'goal', minute: 29 },
      { id: 'h13b', title: 'Brace vs Mansfield Town (2nd)', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-12-06', event_type: 'goal', minute: 64 },
      { id: 'h14', title: 'Overhead Kick vs Stockport', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-09-20', event_type: 'goal', minute: 43 },
      { id: 'h14b', title: 'Goal vs Newport County', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-19', event_type: 'goal', minute: 31 },
      { id: 'h14c', title: 'Assist vs Gillingham', url: 'https://www.youtube.com/embed/dQw4w9WgXcQ', date: '2025-10-05', event_type: 'assist', minute: 56 },
    ],
    notes: '',
    ai_summary: 'Natural goalscorer with predatory instincts in the box. Good aerial ability for his size. Proven at this level with impressive goal record.',
    match_logs: [
      { match_date: '2025-09-14', opponent: 'Mansfield Town', goals: 2, assists: 0, xG: 1.3, xA: 0.1, minutes: 90, rating: 8.5, dribbles: 2, key_passes: 1, tackles: 0, interceptions: 0 },
      { match_date: '2025-09-21', opponent: 'Stockport County', goals: 1, assists: 0, xG: 0.5, xA: 0.0, minutes: 90, rating: 7.8, dribbles: 1, key_passes: 0, tackles: 0, interceptions: 1 },
      { match_date: '2025-09-28', opponent: 'Crawley Town', goals: 0, assists: 0, xG: 0.3, xA: 0.2, minutes: 70, rating: 6.4, dribbles: 1, key_passes: 1, tackles: 1, interceptions: 0 },
      { match_date: '2025-10-05', opponent: 'Gillingham', goals: 0, assists: 1, xG: 0.2, xA: 0.3, minutes: 90, rating: 7.0, dribbles: 0, key_passes: 2, tackles: 0, interceptions: 0 },
      { match_date: '2025-10-19', opponent: 'Newport County', goals: 1, assists: 0, xG: 0.7, xA: 0.0, minutes: 82, rating: 7.4, dribbles: 2, key_passes: 0, tackles: 1, interceptions: 0 },
    ],
  },
];

export const mockTeams: Team[] = [
  { id: 1, name: 'Barrow', league: 'EFL League Two', position: 1, played: 34, won: 20, drawn: 8, lost: 6, goalsFor: 52, goalsAgainst: 28, goalDifference: 24, points: 68, avgXG: 1.42, avgPossession: 52.1, squad: [{ id: 101, name: 'Billy Waters', position: 'Forward', age: 28, nationality: 'England', appearances: 33, goals: 12, assists: 5 }, { id: 102, name: 'Sam Foley', position: 'Midfielder', age: 30, nationality: 'Ireland', appearances: 32, goals: 3, assists: 7 }, { id: 103, name: 'Jason Taylor', position: 'Defender', age: 26, nationality: 'England', appearances: 34, goals: 1, assists: 2 }] },
  { id: 2, name: 'Crawley Town', league: 'EFL League Two', position: 2, played: 34, won: 19, drawn: 9, lost: 6, goalsFor: 55, goalsAgainst: 30, goalDifference: 25, points: 66, avgXG: 1.53, avgPossession: 54.3, squad: [{ id: 1, name: 'James Collins', position: 'Forward', age: 24, nationality: 'England', appearances: 32, goals: 14, assists: 6 }, { id: 104, name: 'Jack Powell', position: 'Midfielder', age: 27, nationality: 'Wales', appearances: 30, goals: 4, assists: 8 }] },
  { id: 3, name: 'Gillingham', league: 'EFL League Two', position: 3, played: 34, won: 18, drawn: 10, lost: 6, goalsFor: 48, goalsAgainst: 26, goalDifference: 22, points: 64, avgXG: 1.35, avgPossession: 51.8 },
  { id: 4, name: 'Doncaster Rovers', league: 'EFL League Two', position: 4, played: 34, won: 18, drawn: 7, lost: 9, goalsFor: 50, goalsAgainst: 34, goalDifference: 16, points: 61, avgXG: 1.44, avgPossession: 50.2 },
  { id: 5, name: 'Wrexham', league: 'EFL League Two', position: 5, played: 34, won: 17, drawn: 8, lost: 9, goalsFor: 46, goalsAgainst: 31, goalDifference: 15, points: 59, avgXG: 1.30, avgPossession: 53.5 },
  { id: 6, name: 'Walsall', league: 'EFL League Two', position: 6, played: 34, won: 16, drawn: 10, lost: 8, goalsFor: 44, goalsAgainst: 32, goalDifference: 12, points: 58, avgXG: 1.25, avgPossession: 49.7 },
  { id: 7, name: 'Swindon Town', league: 'EFL League Two', position: 7, played: 34, won: 16, drawn: 9, lost: 9, goalsFor: 47, goalsAgainst: 35, goalDifference: 12, points: 57, avgXG: 1.38, avgPossession: 48.9 },
  { id: 8, name: 'Bradford City', league: 'EFL League Two', position: 8, played: 34, won: 15, drawn: 10, lost: 9, goalsFor: 42, goalsAgainst: 30, goalDifference: 12, points: 55, avgXG: 1.22, avgPossession: 50.5 },
  { id: 9, name: 'Stockport County', league: 'EFL League Two', position: 9, played: 34, won: 15, drawn: 9, lost: 10, goalsFor: 45, goalsAgainst: 37, goalDifference: 8, points: 54, avgXG: 1.31, avgPossession: 52.0 },
  { id: 10, name: 'Newport County', league: 'EFL League Two', position: 10, played: 34, won: 14, drawn: 10, lost: 10, goalsFor: 40, goalsAgainst: 33, goalDifference: 7, points: 52, avgXG: 1.18, avgPossession: 47.6 },
  { id: 11, name: 'Salford City', league: 'EFL League Two', position: 11, played: 34, won: 14, drawn: 9, lost: 11, goalsFor: 43, goalsAgainst: 38, goalDifference: 5, points: 51, avgXG: 1.26, avgPossession: 49.3 },
  { id: 12, name: 'Morecambe', league: 'EFL League Two', position: 12, played: 34, won: 13, drawn: 10, lost: 11, goalsFor: 38, goalsAgainst: 35, goalDifference: 3, points: 49, avgXG: 1.10, avgPossession: 46.8 },
  { id: 13, name: 'Harrogate Town', league: 'EFL League Two', position: 13, played: 34, won: 13, drawn: 9, lost: 12, goalsFor: 41, goalsAgainst: 40, goalDifference: 1, points: 48, avgXG: 1.20, avgPossession: 48.2 },
  { id: 14, name: 'Tranmere Rovers', league: 'EFL League Two', position: 14, played: 34, won: 12, drawn: 11, lost: 11, goalsFor: 39, goalsAgainst: 37, goalDifference: 2, points: 47, avgXG: 1.15, avgPossession: 47.5 },
  { id: 15, name: 'Grimsby Town', league: 'EFL League Two', position: 15, played: 34, won: 12, drawn: 9, lost: 13, goalsFor: 36, goalsAgainst: 38, goalDifference: -2, points: 45, avgXG: 1.05, avgPossession: 46.1 },
  { id: 16, name: 'Accrington Stanley', league: 'EFL League Two', position: 16, played: 34, won: 11, drawn: 10, lost: 13, goalsFor: 35, goalsAgainst: 39, goalDifference: -4, points: 43, avgXG: 1.02, avgPossession: 45.5 },
  { id: 17, name: 'AFC Wimbledon', league: 'EFL League Two', position: 17, played: 34, won: 11, drawn: 9, lost: 14, goalsFor: 34, goalsAgainst: 42, goalDifference: -8, points: 42, avgXG: 0.98, avgPossession: 44.8 },
  { id: 18, name: 'Colchester United', league: 'EFL League Two', position: 18, played: 34, won: 10, drawn: 10, lost: 14, goalsFor: 33, goalsAgainst: 43, goalDifference: -10, points: 40, avgXG: 0.95, avgPossession: 44.2 },
  { id: 19, name: 'Notts County', league: 'EFL League Two', position: 19, played: 34, won: 9, drawn: 11, lost: 14, goalsFor: 31, goalsAgainst: 40, goalDifference: -9, points: 38, avgXG: 0.91, avgPossession: 43.5 },
  { id: 20, name: 'Crewe Alexandra', league: 'EFL League Two', position: 20, played: 34, won: 9, drawn: 9, lost: 16, goalsFor: 30, goalsAgainst: 45, goalDifference: -15, points: 36, avgXG: 0.88, avgPossession: 43.0 },
  { id: 21, name: 'Sutton United', league: 'EFL League Two', position: 21, played: 34, won: 8, drawn: 10, lost: 16, goalsFor: 28, goalsAgainst: 44, goalDifference: -16, points: 34, avgXG: 0.82, avgPossession: 42.3 },
  { id: 22, name: 'Hartlepool United', league: 'EFL League Two', position: 22, played: 34, won: 7, drawn: 10, lost: 17, goalsFor: 27, goalsAgainst: 48, goalDifference: -21, points: 31, avgXG: 0.78, avgPossession: 41.5 },
  { id: 23, name: 'Rochdale', league: 'EFL League Two', position: 23, played: 34, won: 6, drawn: 9, lost: 19, goalsFor: 25, goalsAgainst: 50, goalDifference: -25, points: 27, avgXG: 0.72, avgPossession: 40.8 },
  { id: 24, name: 'Oldham Athletic', league: 'EFL League Two', position: 24, played: 34, won: 5, drawn: 8, lost: 21, goalsFor: 22, goalsAgainst: 55, goalDifference: -33, points: 23, avgXG: 0.65, avgPossession: 39.5 },
];

export const mockLeagueTable: LeagueEntry[] = mockTeams.map((t) => ({
  position: t.position,
  team: t.name,
  played: t.played,
  won: t.won,
  drawn: t.drawn,
  lost: t.lost,
  goalsFor: t.goalsFor,
  goalsAgainst: t.goalsAgainst,
  goalDifference: t.goalDifference,
  points: t.points,
}));
